with source as (

    select * from {{ source('raw_ho_mdm', 'fmaster') }}

),

cleaned as (

    select
        cast(pcode as varchar(6)) as pcode,
        cast(pcodename as varchar(40)) as pcodename,
        cast(cpro as varchar(3)) as cpro,
        cast(matgr as varchar(9)) as matgr,
        cast(prlin as varchar(3)) as prlin,
        cast(brand as varchar(3)) as brand,
        cast(sbra1 as varchar(3)) as sbra1,
        cast(prkat as varchar(3)) as prkat,
        cast(sbra2 as varchar(3)) as sbra2,
        cast(flavr as varchar(3)) as flavr,
        cast(packs as varchar(3)) as packs,
        cast(packt as varchar(3)) as packt,
        cast(princ as varchar(3)) as princ,
        cast(suppno as varchar(6)) as suppno,
        cast(rptname1 as varchar(10)) as rptname1,
        cast(rptname2 as varchar(10)) as rptname2,
        cast(rptname3 as varchar(10)) as rptname3,
        cast(sortno as numeric) as sortno,
        cast(unit1 as varchar(3)) as unit1,
        cast(unit2 as varchar(3)) as unit2,
        cast(unit3 as varchar(3)) as unit3,
        cast(convunit2 as numeric) as convunit2,
        cast(convunit3 as numeric) as convunit3,
        cast(weight1 as numeric) as weight1,
        cast(weight2 as numeric) as weight2,
        cast(weight3 as numeric) as weight3,
        cast(buyprice1 as numeric) as buyprice1,
        cast(buyprice2 as numeric) as buyprice2,
        cast(buyprice3 as numeric) as buyprice3,
        cast(sellprice1 as numeric) as sellprice1,
        cast(sellprice2 as numeric) as sellprice2,
        cast(sellprice3 as numeric) as sellprice3,
        cast(mweekno as numeric) as mweekno,
        cast(lweekno as numeric) as lweekno,
        cast(pbm as numeric) as pbm,
        cast(pbmjual as numeric) as pbmjual,
        cast(plines as numeric) as plines,
        cast(minstock as numeric) as minstock,
        cast(xminstock as varchar(14)) as xminstock,
        cast(sftstock as numeric) as sftstock,
        cast(xsftstock as varchar(14)) as xsftstock,
        cast(flagaktif as varchar(1)) as flagaktif,
        cast(flagmain as varchar(1)) as flagmain,
        cast(flagnew as varchar(1)) as flagnew,
        cast(flagbatch as varchar(1)) as flagbatch,
        cast(jatah as varchar(1)) as jatah,
        cast(tipeob as varchar(1)) as tipeob,
        cast(grins as varchar(2)) as grins,
        cast(rpp as numeric) as rpp,
        cast(pcparent as varchar(6)) as pcparent,
        cast(hpp as numeric) as hpp,
        cast(data01 as numeric) as data01,
        cast(data02 as numeric) as data02,
        cast(data03 as numeric) as data03,
        cast(data04 as numeric) as data04,
        cast(data05 as numeric) as data05,
        cast(data06 as numeric) as data06,
        cast(data07 as varchar(30)) as data07,
        cast(data08 as date) as data08,
        cast(data09 as varchar(1)) as data09,
        cast(data10 as varchar(1)) as data10,
        cast(data11 as varchar(18)) as data11,
        cast(data12 as varchar(1)) as data12,
        cast(data13 as timestamp(6)) as data13,
        cast(data14 as varchar(1)) as data14,
        cast(datecreate as timestamp(6)) as datecreate,
        cast(usercreate as varchar(15)) as usercreate,
        cast(updatedate as timestamp(6)) as updatedate,
        cast(userupdate as varchar(15)) as userupdate,
        cast(timecreate as varchar(15)) as timecreate,
        cast(timeupdate as varchar(20)) as timeupdate,
        _airbyte_extracted_at

    from source

)

select * from cleaned
